name: example
description: substring_highlight example

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  slowly_moving_widgets_field: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  slowly_moving_widgets_field:
    path: ../

flutter:
  uses-material-design: true
